### PR TITLE
HPCC-14305 6.0.0-beta1 does not build on centos 5

### PR DESCRIPTION
**Pull request by richardkchapman**
CPU_COUNT macro not available on earlier versions of glibc. Code stolen from
jlib.

Signed-off-by: Richard Chapman rchapman@hpccsystems.com

### CODE REVIEW

**Comment by richardkchapman** [comment]
@cloLN Please test - I don't have a Centos5 system

**Comment by cloLN** [comment]
Just tried to build on centos5.

[ 82%] Building CXX object esp/services/ws_fs/CMakeFiles/ws_fs.dir/__/__/__/generated/ws_fs_esp.cpp.o
cc1plus: warning: -Wuninitialized is not supported without -O
[ 83%] Building CXX object esp/services/ws_fs/CMakeFiles/ws_fs.dir/ws_fsBinding.cpp.o
Scanning dependencies of target ws_topology
[ 83%] Building CXX object esp/services/ws_topology/CMakeFiles/ws_topology.dir/__/__/__/generated/ws_topology_esp.cpp.o
cc1plus: warning: -Wuninitialized is not supported without -O
[ 83%] Building CXX object esp/services/ws_dfu/CMakeFiles/ws_dfu.dir/ws_dfuXRefService.cpp.o
make[1]: *** [roxie/ccd/CMakeFiles/ccd.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 83%] Building CXX object esp/services/ws_topology/CMakeFiles/ws_topology.dir/ws_topologyPlugin.cpp.o
[ 83%] Building CXX object esp/services/ws_topology/CMakeFiles/ws_topology.dir/ws_topologyService.cpp.o
Linking CXX shared library ../../../Release/libs/libws_dfu.so
[ 83%] Built target ws_dfu
[ 83%] Building CXX object esp/services/ws_fs/CMakeFiles/ws_fs.dir/ws_fsPlugin.cpp.o
[ 83%] Building CXX object esp/services/ws_fs/CMakeFiles/ws_fs.dir/ws_fsService.cpp.o
Linking CXX shared library ../../../Release/libs/libws_fs.so
Linking CXX shared library ../../../Release/libs/libws_topology.so
[ 83%] Built target ws_fs
[ 83%] Built target ws_topology
make: *** [all] Error 2


This was using this cmake command:
cmake ../HPCC-Platform/ -DUSE_OPENLDAP=OFF

**Comment by richardkchapman** [comment]
Unfortunately the snippet of log you have posted does not tell me what the error was. Can you try the make without -j and post the tail of the log

**Comment by cloLN** [comment]
Scanning dependencies of target ws_workunits
[ 67%] Building CXX object esp/services/ws_workunits/CMakeFiles/ws_workunits.dir/__/__/__/dali/sasha/sacmd.cpp.o
[ 67%] Building CXX object esp/services/ws_workunits/CMakeFiles/ws_workunits.dir/__/__/__/dali/dfu/dfuutil.cpp.o
[ 67%] Building CXX object esp/services/ws_workunits/CMakeFiles/ws_workunits.dir/__/__/__/generated/common_esp.cpp.o
cc1plus: warning: -Wuninitialized is not supported without -O
[ 68%] Building CXX object esp/services/ws_workunits/CMakeFiles/ws_workunits.dir/__/__/__/generated/ws_workunits_esp.cpp.o
cc1plus: warning: -Wuninitialized is not supported without -O
[ 68%] Building CXX object esp/services/ws_workunits/CMakeFiles/ws_workunits.dir/__/__/__/generated/ws_fs_esp.cpp.o
cc1plus: warning: -Wuninitialized is not supported without -O
[ 68%] Building CXX object esp/services/ws_workunits/CMakeFiles/ws_workunits.dir/__/__/clients/roxiecontrol.cpp.o
[ 68%] Building CXX object esp/services/ws_workunits/CMakeFiles/ws_workunits.dir/ws_workunitsPlugin.cpp.o
[ 68%] Building CXX object esp/services/ws_workunits/CMakeFiles/ws_workunits.dir/ws_workunitsService.cpp.o
[ 68%] Building CXX object esp/services/ws_workunits/CMakeFiles/ws_workunits.dir/ws_workunitsHelpers.cpp.o
[ 68%] Building CXX object esp/services/ws_workunits/CMakeFiles/ws_workunits.dir/ws_workunitsAuditLogs.cpp.o
[ 68%] Building CXX object esp/services/ws_workunits/CMakeFiles/ws_workunits.dir/ws_workunitsQuerySets.cpp.o
Linking CXX shared library ../../../Release/libs/libws_workunits.so
[ 68%] Built target ws_workunits
Scanning dependencies of target ws_smc
[ 68%] Building CXX object esp/services/ws_smc/CMakeFiles/ws_smc.dir/__/__/__/generated/ws_smc_esp.cpp.o
cc1plus: warning: -Wuninitialized is not supported without -O
[ 68%] Building CXX object esp/services/ws_smc/CMakeFiles/ws_smc.dir/__/__/clients/roxiecontrol.cpp.o
[ 69%] Building CXX object esp/services/ws_smc/CMakeFiles/ws_smc.dir/ws_smcPlugin.cpp.o
[ 69%] Building CXX object esp/services/ws_smc/CMakeFiles/ws_smc.dir/ws_smcService.cpp.o
Linking CXX shared library ../../../Release/libs/libws_smc.so
[ 69%] Built target ws_smc
[ 70%] Built target WsDeploy
Scanning dependencies of target ws_packageprocess
[ 70%] Building CXX object esp/services/ws_packageprocess/CMakeFiles/ws_packageprocess.dir/__/__/__/dali/dfu/dfuutil.cpp.o
[ 70%] Building CXX object esp/services/ws_packageprocess/CMakeFiles/ws_packageprocess.dir/__/__/__/generated/ws_fs_esp.cpp.o
cc1plus: warning: -Wuninitialized is not supported without -O
[ 70%] Building CXX object esp/services/ws_packageprocess/CMakeFiles/ws_packageprocess.dir/__/__/__/generated/ws_packageprocess_esp.cpp.o
cc1plus: warning: -Wuninitialized is not supported without -O
[ 70%] Building CXX object esp/services/ws_packageprocess/CMakeFiles/ws_packageprocess.dir/ws_packageprocessPlugin.cpp.o
[ 70%] Building CXX object esp/services/ws_packageprocess/CMakeFiles/ws_packageprocess.dir/ws_packageprocessService.cpp.o
Linking CXX shared library ../../../Release/libs/libws_packageprocess.so
[ 70%] Built target ws_packageprocess
[ 70%] Built target ws_esdlconfig
[ 71%] Built target esdl_svc_engine
[ 72%] Built target ws_espcontrol
[ 73%] Built target httptest
[ 73%] Built target soapplus
[ 74%] Built target auditlib
[ 74%] Built target debugservices
[ 75%] Built target dmetaphone
[ 75%] Built target fileservices
[ 75%] Built target logging
[ 75%] Built target parselib
[ 75%] Built target stringlib
[ 75%] Built target timelib
[ 75%] Built target unicodelib
[ 75%] Built target workunitservices
[ 75%] Built target mysqlembed
[ 75%] Built target pyembed
[ 75%] Built target javaembed
[ 75%] Built target Rembed
[ 75%] Built target libuv
[ 82%] Built target cpp-driver
[ 82%] Built target cassandra
[ 82%] Built target cassandraembed
[ 82%] Built target cassandra_static
[ 83%] Built target udplib
[ 83%] Building CXX object roxie/ccd/CMakeFiles/ccd.dir/ccdlistener.cpp.o
/mnt/ephemeral0/clo/HPCC-Platform/roxie/ccd/ccdlistener.cpp: In static member function âstatic void RoxieListener::updateAffinity()â:
/mnt/ephemeral0/clo/HPCC-Platform/roxie/ccd/ccdlistener.cpp:680: error: âcpusetâ was not declared in this scope
make[2]: *** [roxie/ccd/CMakeFiles/ccd.dir/ccdlistener.cpp.o] Error 1
make[1]: *** [roxie/ccd/CMakeFiles/ccd.dir/all] Error 2
make: *** [all] Error 2

**Comment by richardkchapman** [comment]
@cloLN Repushed - please check again

**Comment by cloLN** [comment]
It built fine on the centos5 build box.

**Comment by richardkchapman** [comment]
@ghalliday Please review/merge

**Comment by ghalliday** [comment]
@richardkchapman  
Should this be targeting an older version?  I think the change is in 5.2.x and others.

**Comment by cloLN** [comment]
We didn't really hit this issue until 6.0.  @xwang2713 do you agree?

**Comment by xwang2713** [comment]
Right, This only happens for HPCC 6.0.0 build. HPCC Platform CE/EE/LN builds OK for previous versions

**Comment by richardkchapman** [comment]
Code that causes the issue was introduced in commit d9069fb, HPCC-12599 Option in Roxie to bind queries to cores

git branch --contains confirms that 6.0.0 is the first candidate branch affected, as does the JIRA ticket.

@ghalliday Back to you...
