### PR TITLE
HPCC-21879 Enable warnings on eclrtl

### PR DESCRIPTION
**Pull request by richardkchapman**
More issues picked up by gcc 7.3

Signed-off-by: Richard Chapman <rchapman@hpccsystems.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [x] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by richardkchapman** [comment]
@xwang2713 Please review/test

**Review by xwang2713 — COMMENTED** [review]
Several more places :
HPCC-Platform/rtl/eclrtl/eclrtl.cpp:367:57: error: ‘UBool unorm_isNormalized_60(const UChar*, int32_t, UNormalizationMode, UErrorCode*)’ is deprecated [-Werror=deprecated-declarations]
HPCC-Platform/rtl/eclrtl/eclrtl.cpp:372:54: error: ‘UBool unorm_isNormalized_60(const UChar*, int32_t, UNormalizationMode, UErrorCode*)’ is deprecated [-Werror=deprecated-declarations]
HPCC-Platform/rtl/eclrtl/eclrtl.cpp:378:77: error: ‘int32_t unorm_normalize_60(const UChar*, int32_t, UNormalizationMode, int32_t, UChar*, int32_t, UErrorCode*)’ is deprecated [-Werror=deprecated-declarations]
HPCC-Platform/rtl/eclrtl/eclrtl.cpp:387:76: error: ‘int32_t unorm_normalize_60(const UChar*, int32_t, UNormalizationMode, int32_t, UChar*, int32_t, UErrorCode*)’ is deprecated [-Werror=deprecated-declarations]
HPCC-Platform/rtl/eclrtl/eclrtl.cpp:395:64: error: ‘int32_t unorm_normalize_60(const UChar*, int32_t, UNormalizationMode, int32_t, UChar*, int32_t, UErrorCode*)’ is deprecated [-Werror=deprecated-declarations]
HPCC-Platform/rtl/eclrtl/eclrtl.cpp:397:62: error: ‘int32_t unorm_normalize_60(const UChar*, int32_t, UNormalizationMode, int32_t, UChar*, int32_t, UErrorCode*)’ is deprecated [-Werror=deprecated-declarations]
HPCC-Platform/rtl/eclrtl/eclrtl.cpp:402:73: error: ‘int32_t unorm_normalize_60(const UChar*, int32_t, UNormalizationMode, int32_t, UChar*, int32_t, UErrorCode*)’ is deprecated [-Werror=deprecated-declarations]
HPCC-Platform/rtl/eclrtl/eclrtl.cpp:404:62: error: ‘int32_t unorm_normalize_60(const UChar*, int32_t, UNormalizationMode, int32_t, UChar*, int32_t, UErrorCode*)’ is deprecated [-Werror=deprecated-declarations]
HPCC-Platform/rtl/eclrtl/eclrtl.cpp:449:62: error: ‘int32_t unorm_normalize_60(const UChar*, int32_t, UNormalizationMode, int32_t, UChar*, int32_t, UErrorCode*)’ is deprecated [-Werror=deprecated-declarations]
HPCC-Platform/rtl/eclrtl/eclrtl.cpp:1533:99: error: ‘int32_t unorm_concatenate_60(const UChar*, int32_t, const UChar*, int32_t, UChar*, int32_t, UNormalizationMode, int32_t, UErrorCode*)’ is deprecated [-Werror=deprecated-declarations]
HPCC-Platform/rtl/eclrtl/eclrtl.cpp:1568:99: error: ‘int32_t unorm_concatenate_60(const UChar*, int32_t, const UChar*, int32_t, UChar*, int32_t, UNormalizationMode, int32_t, UErrorCode*)’ is deprecated [-Werror=deprecated-declarations]
HPCC-Platform/rtl/eclrtl/eclrtl.cpp:1649:86: error: ‘int32_t unorm_concatenate_60(const UChar*, int32_t, const UChar*, int32_t, UChar*, int32_t, UNormalizationMode, int32_t, UErrorCode*)’ is deprecated [-Werror=deprecated-declarations]
HPCC-Platform/rtl/eclrtl/eclrtl.cpp:1671:86: error: ‘int32_t unorm_concatenate_60(const UChar*, int32_t, const UChar*, int32_t, UChar*, int32_t, UNormalizationMode, int32_t, UErrorCode*)’ is deprecated [-Werror=deprecated-declarations]
HPCC-Platform/rtl/eclrtl/eclrtl.cpp:1723:80: error: ‘int32_t unorm_concatenate_60(const UChar*, int32_t, const UChar*, int32_t, UChar*, int32_t, UNormalizationMode, int32_t, UErrorCode*)’ is deprecated [-Werror=deprecated-declarations]
HPCC-Platform/rtl/eclrtl/eclrtl.cpp:5320:130: error: ‘int32_t unorm_concatenate_60(const UChar*, int32_t, const UChar*, int32_t, UChar*, int32_t, UNormalizationMode, int32_t, UErrorCode*)’ is deprecated [-Werror=deprecated-declarations]

**Comment by richardkchapman** [comment]
@ghalliday I don't know why these are deprecated - I suspect we probably want to disable that error for now, unless you think differently?

**Comment by xwang2713** [comment]
Retested it. Above was fixed.  Now it has following errors:
1) On Ubuntu 18.04 (GCC 7.3.0): 
/HPCC-Platform/rtl/eclrtl/./../../system/jlib/jiface.hpp:37:33: error: this statement may fall through [-Werror=implicit-fallthrough=]
09:44:05   #define assertex(p) (likely(p) ? ((void) 0) : (( (void) raiseAssertException(#p, __FILE__, __LINE__))))
09:44:05                       ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
09:44:05 /mnt/disk1/jenkins/workspace/CE-Candidate-JIRA-21905/CE/ubuntu-18.04-amd64/HPCC-Platform/rtl/eclrtl/rtldistr.cpp:412:9: note: in expansion of macro ‘assertex’
09:44:05          assertex(false); // TBD
09:44:05          ^~~~~~~~
09:44:05 /mnt/disk1/jenkins/workspace/CE-Candidate-JIRA-21905/CE/ubuntu-18.04-amd64/HPCC-Platform/rtl/eclrtl/rtldistr.cpp:413:5: note: here
09:44:05      case 1:

2) On Ubuntu 18.10 (GCC 8.2.0):
HPCC-Platform/rtl/eclrtl/rtlbcd.cpp:301:67: error: ‘void* memcpy(void*, const void*, size_t)’ writing to an object of non-trivially copyable type ‘class Decimal’; use copy-assignment or copy-initialization instead [-Werror=class-memaccess]
09:23:58      memcpy(&stack[curStack-1], &stack[curStack-2], sizeof(Decimal));
09:23:58                                                                    ^
09:23:58 In file included from /mnt/disk1/jenkins/workspace/CE-Candidate-JIRA-21905/CE/ubuntu-18.10-amd64/HPCC-Platform/rtl/eclrtl/rtlbcd.cpp:21:
09:23:58 /mnt/disk1/jenkins/workspace/CE-Candidate-JIRA-21905/CE/ubuntu-18.10-amd64/HPCC-Platform/rtl/eclrtl/./../../rtl/nbcd/nbcd.hpp:47:17: note: ‘class Decimal’ declared here
09:23:58  class nbcd_decl Decimal
09:23:58                  ^~~~~~~
09:23:58 /mnt/disk1/jenkins/workspace/CE-Candidate-JIRA-21905/CE/ubuntu-18.10-amd64/HPCC-Platform/rtl/eclrtl/rtlbcd.cpp:302:54: error: ‘void* memcpy(void*, const void*, size_t)’ writing to an object of non-trivially copyable type ‘class Decimal’; use copy-assignment or copy-initialization instead [-Werror=class-memaccess]
09:23:58      memcpy(&stack[curStack-2], &temp, sizeof(Decimal));
09:23:58                                                       ^
09:23:58 In file included from /mnt/disk1/jenkins/workspace/CE-Candidate-JIRA-21905/CE/ubuntu-18.10-amd64/HPCC-Platform/rtl/eclrtl/rtlbcd.cpp:21:
09:23:58 /mnt/disk1/jenkins/workspace/CE-Candidate-JIRA-21905/CE/ubuntu-18.10-amd64/HPCC-Platform/rtl/eclrtl/./../../rtl/nbcd/nbcd.hpp:47:17: note: ‘class Decimal’ declared here
09:23:58  class nbcd_decl Decimal
09:23:58                  ^~~~~~~

**Comment by ghalliday** [comment]
unorm_normalize_60() - actually the function unorm_normalize().  If you look at the documentation this has been deprecated from 5.8 in favour of a new normalization interface.  I suspect we should not be defaulting that option to an error.
(See http://www.icu-project.org/apiref/icu4c/unorm_8h.html#a5410fab40c4e60a787c5cfbea5103c75)

**Comment by ghalliday** [comment]
rtldistr.cpp(413) - change to throwUnexpected()
nbcd.hpp(51) - delete the copy constructor, the default should be correct (also nbcd.cpp(35-39))

**Comment by ghalliday** [comment]
Also jiface.hpp (30,31)

void jlib_decl raiseAssertException(const char *assertion, const char *file, unsigned line);
void jlib_decl raiseAssertCore(const char *assertion, const char *file, unsigned line);

should gain no return attribuites:

__declspec(noreturn) void jlib_decl raiseAssertException(const char *assertion, const char *file, unsigned line) __attribute__((noreturn));
__declspec(noreturn) void jlib_decl raiseAssertCore(const char *assertion, const char *file, unsigned line) __attribute__((noreturn));

**Comment by ghalliday** [comment]
@richardkchapman see comments

**Comment by richardkchapman** [comment]
@xwang2713 Fixed as suggested by Gavin and repushed. Please try again

**Comment by AttilaVamos** [comment]
@richardkchapman Smoketest generated an exception in processing the test logs that's why no test result. 
I'm working on to fix this problem.

**Comment by richardkchapman** [comment]
Rebased on top of HPCC-21944 - the smoketest errors were caused by an unrelated bug revealed by one of these changes

**Comment by richardkchapman** [comment]
@ghalliday Please review

**Comment by richardkchapman** [comment]
@xwang2713 Can you check for any remaining gcc issues

**Comment by xwang2713** [comment]
Only one error  on Ubuntu 18.10:

HPCC-Platform/rtl/eclrtl/rtlbcd.cpp:302:54: error: ‘void* memcpy(void*, const void*, size_t)’ copying an object of non-trivial type ‘class Decimal’ from an array of ‘char [67]’ [-Werror=class-memaccess]
09:58:24      memcpy(&stack[curStack-2], &temp, sizeof(Decimal));
09:58:24                                                       ^
09:58:24 In file included from /mnt/disk1/jenkins/workspace/CE-Candidate-JIRA-21905/CE/ubuntu-18.10-amd64/HPCC-Platform/rtl/eclrtl/rtlbcd.cpp:21:
09:58:24 /mnt/disk1/jenkins/workspace/CE-Candidate-JIRA-21905/CE/ubuntu-18.10-amd64/HPCC-Platform/rtl/eclrtl/./../../rtl/nbcd/nbcd.hpp:47:17: note: ‘class Decimal’ declared here
09:58:24  class nbcd_decl Decimal
09:58:24                  ^~~~~~~
09:58:25 cc1plus: all warnings being treated as errors

**Comment by richardkchapman** [comment]
@ghalliday Please review latest commit. I don't think this function is actually used.

@xwang2713 Released another fix. Please check if it compiles now.

**Comment by xwang2713** [comment]
Builds OK on all distros: http://10.240.32.243/view/custom/job/CE-Candidate-JIRA-21905/

**Comment by richardkchapman** [comment]
@ghalliday Please merge
