### PR TITLE
HPCC-17532 Build Windows Client with Pyembed

### PR DESCRIPTION
**Pull request by richardkchapman**
Signed-off-by: Richard Chapman <rchapman@hpccsystems.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browers
  - [ ] The component(s) render as expected

## Testing:
I have not tested due to lack of a Windows system - @xwang2713 has...

### CODE REVIEW

**Comment by richardkchapman** [comment]
@ghalliday Can you check this compiles - I have no way to test.

**Comment by xwang2713** [comment]
I will test it. Just need cherry-pick from HPCC-17529

**Comment by xwang2713** [comment]
Windows 32bit build run OK. 64bit build has error:  c:\python27-win64\include\pyconfig.h(203): error C2371: 'ssize_t': redefinition; different basic types

**Comment by xwang2713** [comment]
For a work-around I comment out "ssize_t" definition in pyconfig.h of Python2.7 64bit on build server. Now Clienttools builds OK with Python 2.7 64bit.

**Comment by richardkchapman** [comment]
That's not a good workaround... #define / #undef is better

**Comment by xwang2713** [comment]
OK

**Comment by ghalliday** [comment]
@xwang2713 reassigning since you are testing it.

**Comment by xwang2713** [comment]
@richardkchapman tested again with pyconfig.h changes in Python 64bit package on build system. 

> #ifndef _PLATFORM_H_   
#ifdef MS_WIN64
typedef __int64 ssize_t;
#else
typedef _W64 int ssize_t;
#endif
#endif

>


The build run OK.

**Comment by richardkchapman** [comment]
You misunderstand - the point is we can't rely on changing pyconfig.h since it's not  file we control. We have to make changes to a file that we DO control to work around this issue.

I'll push something that shows what I mean, but I can't test it

**Comment by richardkchapman** [comment]
@xwang2713 See second commit

**Review by xwang2713 — COMMENTED** [review]
OK. I will test it

**Comment by xwang2713** [comment]
The build run successfully.

**Comment by richardkchapman** [comment]
@ghalliday Please review/merge

**Comment by ghalliday** [comment]
@richardkchapman looks good, but checkboxes not filled in.

**Comment by richardkchapman** [comment]
@ghalliday Done
