### PR TITLE
HPCC-13427 Release some example queries

### PR DESCRIPTION
**Pull request by aranjan1002**
Adding some example queries to regression suite. They are aimed at identifying issues related to child query execution.

### CODE REVIEW

**Comment by AttilaVamos** [comment]
Automated Smoketest Build: success
HPCC Start: OK

| setup | hthor | thor | roxie |
| ----- | ----- | ----- | ---- |
| setup | Pass | Pass | Pass |
| setup_fetch | Pass | Pass | Pass |
| setupdict | Pass | Pass | Pass |
| setupsearchindex | Pass | Pass | Pass |
| setupsq | Pass | Pass | Pass |
| setupwordindex | Pass | Pass | Pass |
| setupxml | Pass | Pass | Pass |
 

| test | hthor | thor | roxie |
| ----- | ----- | ----- | ---- |
| gsoc1 | Pass | Pass | Pass |
| gsoc2 | Pass | Pass | Pass |
| gsoc3 | Pass | Pass | Pass |
| gsoc4 | Fail | Pass | Pass |
| gsoc5 | Pass | Pass | Pass |
| gsoc6 | Pass | Pass | Pass |
 
HPCC Stop: OK

**Comment by AttilaVamos** [comment]
All right. If you wish to reviewers and other guys like you then it would be good to do some other changes:
1. Edit the pull request title, description and add same text as the commit ('HPCC-.....')

2. Squash your four commit into one:
You can do this fairly easily. To squash the last 4 commits.
	git reset --soft HEAD~4

If you want to write the new commit message from scratch, this suffices:
	git commit -a -s 
and edit the message accordingly our guidelines:
https://github.com/hpcc-systems/HPCC-Platform/wiki/Git-commit-message-guidelines

**Comment by AttilaVamos** [comment]
Automated Smoketest Build: success
HPCC Start: OK

| setup | hthor | thor | roxie |
| ----- | ----- | ----- | ---- |
| setup | Pass | Pass | Pass |
| setup_fetch | Pass | Pass | Pass |
| setupdict | Pass | Pass | Pass |
| setupsearchindex | Pass | Pass | Pass |
| setupsq | Pass | Pass | Pass |
| setupwordindex | Pass | Pass | Pass |
| setupxml | Pass | Pass | Pass |
 

| test | hthor | thor | roxie |
| ----- | ----- | ----- | ---- |
| gsoc1 | Pass | Pass | Pass |
| gsoc2 | Pass | Pass | Pass |
| gsoc3 | Pass | Pass | Pass |
| gsoc4 | Fail | Pass | Pass |
| gsoc5 | Pass | Pass | Pass |
| gsoc6 | Pass | Pass | Pass |
 
HPCC Stop: OK

**Comment by ghalliday** [comment]
@AttilaVamos does the smoke test provide any more detail why something failed?

**Comment by AttilaVamos** [comment]
Actually it doesn't (not yet) for ecl test cases. 
In this particular case the problem is:
Error:
  4. Test: gsoc4.ecl
Error (1001): Command return code non-zero. 
 '
Deploying ECL Archive /home/ati/smoketest/smoketest-7401/HPCCSystems-regression/archives/archive_gsoc4.xml

Deployed
   wuid: W20150604-200513
   state: failed

eclcc: /home/ati/smoketest/smoketest-7401/HPCC-Platform/testing/regress/ecl/gsoc4.ecl(44,10): Error C4839:  INTERNAL: Attempt to access result from unavailable graph (4)
1 error(s), 0 warning(s)

'

**Comment by ghalliday** [comment]
Thanks

**Comment by AttilaVamos** [comment]
@aranjan1002 assign back to you.

**Comment by ghalliday** [comment]
The failure in hthor is fixed by https://github.com/hpcc-systems/HPCC-Platform/pull/7417
